version: "3.7"
services:
  api:
    build: .
    working_dir: /root
    volumes:
      - ./:/root
      - ~/.m2:/root/.m2
    expose:
      - '8080'
    command: mvn clean spring-boot:run
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    expose:
      - '5432'
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssword123
      PGDATA: /data/postgres
    volumes:
      - './sql/:/docker-entrypoint-initdb.d/'
  web:
    image: nginx
    ports:
      - '80:80'
      - '8080:8080'
    restart: on-failure
    volumes:
      - './nginx/:/etc/nginx/conf.d/'
      - '../frontend/dist/webapp-frontend/:/var/www/html/'
    depends_on:
      - api
